import path from "node:path";
import { describe, expect, test } from "vitest";
import { loadFixtureCases } from "./helpers/fixtures.js";
import { compileFixture } from "./helpers/processing.js";

const parserFixtureMetadata = {
  expectedFailures: {},
  quarantined: {},
};

const parserRootDir = path.resolve(process.cwd(), "tests/parser");
const parserFixtures = loadFixtureCases(parserRootDir).map((fixture) => ({
  ...fixture,
  expectedFailure: parserFixtureMetadata.expectedFailures[fixture.name],
  quarantined: parserFixtureMetadata.quarantined[fixture.name],
}));

describe("parser fixture compilation", () => {
  test("metadata only references known fixtures", () => {
    const knownFixtures = new Set(parserFixtures.map((fixture) => fixture.name));

    for (const fixtureName of Object.keys(parserFixtureMetadata.expectedFailures)) {
      expect(knownFixtures.has(fixtureName)).toBe(true);
    }

    for (const fixtureName of Object.keys(parserFixtureMetadata.quarantined)) {
      expect(knownFixtures.has(fixtureName)).toBe(true);
    }
  });

  for (const fixture of parserFixtures) {
    const runner = fixture.quarantined ? test.skip : test;

    runner(fixture.name, () => {
      if (fixture.expectedFailure) {
        expect(() => compileFixture(fixture.filePath)).toThrowError(fixture.expectedFailure);
        return;
      }

      const sketch = compileFixture(fixture.filePath);
      expect(sketch).toBeDefined();
      expect(sketch.sourceCode).toEqual(expect.any(String));
      expect(sketch.sourceCode).toContain("// this code was autogenerated from PJS");
    });
  }
});
